#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COMMON_SCRIPT="$SCRIPT_DIR/start_memory_node.sh"

NUM_CLIENTS="${NUM_CLIENTS:-1}"
PORT="${PORT:-1235}"
MN_MEMORY="${MN_MEMORY:-50}"
STORAGE_ID="${STORAGE_ID:-1}"
ENABLE_STORAGE_OWNER="${ENABLE_STORAGE_OWNER:-0}"
STORAGE_PEER_HOST="${STORAGE_PEER_HOST:-127.0.0.1}"
STORAGE_PEERS="${STORAGE_PEERS:-$STORAGE_PEER_HOST:2234 $STORAGE_PEER_HOST:2235 $STORAGE_PEER_HOST:2236 $STORAGE_PEER_HOST:2237 $STORAGE_PEER_HOST:2238}"

ARGS=(
  --num-clients "$NUM_CLIENTS"
  --port "$PORT"
  --mn-memory "$MN_MEMORY"
)

if [[ "$ENABLE_STORAGE_OWNER" == "1" ]]; then
  # shellcheck disable=SC2206
  STORAGE_PEER_ARGS=( $STORAGE_PEERS )
  ARGS+=(--storage-id "$STORAGE_ID" --storage-peers "${STORAGE_PEER_ARGS[@]}")
fi

exec "$COMMON_SCRIPT" "$@" "${ARGS[@]}"
